Adding Repository for Books.
wolox-training/rr-java pull request #4
Opened 2020-01-08 19:16 UTC by holywyvern

## Summary

This adds the Book repository.
It provides all basic crud methods plus the additional method to find a book by its author.

## Trello Card

https://trello.com/c/WscQduCV/15-crear-un-repositorio-de-books

2020-01-10 13:39 UTC, jeymarsonwolox requested changes

2020-01-10 13:39 UTC, jeymarsonwolox commented on src/main/java/wolox/training/repositories/BookRepository.java
> +    @Query(value = "SELECT b FROM Book b WHERE b.author = ?1")
`@Query` is not necesary, with `findByAuthor` function the framework searches by author

2020-01-10 18:58 UTC, jeymarsonwolox approved these changes

2020-01-14 14:52 UTC, Jimenarosello requested changes

2020-01-14 14:52 UTC, Jimenarosello commented on src/main/java/wolox/training/repositories/BookRepository.java
> +    Book findByAuthor(@NotNull String author);
Return an Optional<Book> instead of a Book :)

2020-01-14 15:01 UTC, Jimenarosello approved these changes

2020-01-14 15:11 UTC, merged