Add user model
wolox-training/rr-java pull request #6
Opened 2020-01-09 15:27 UTC by holywyvern

## Summary

This adds the user model with the corresponding relationship for books.
This also adds the methods to add/remove a book or for a user.

## Trello Card

https://trello.com/c/FiR3oLIg/19-crear-modelo-de-user

2020-01-10 15:35 UTC, Jimenarosello requested changes

2020-01-10 15:35 UTC, Jimenarosello commented on src/main/java/wolox/training/models/User.java
> +    public void setId(long id) {
This setter should not be included since you don't want to allow id changes

2020-01-10 18:59 UTC, jeymarsonwolox approved these changes

2020-01-14 14:24 UTC, Jimenarosello approved these changes

2020-01-14 15:13 UTC, merged

2020-03-16 14:50 UTC, rodrigofranc commented on src/main/java/wolox/training/models/User.java
> +    @ManyToMany(cascade = CascadeType.ALL)
In this scenario we need the cascade type REFRESH and MERGE